export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import { Toaster } from 'react-hot-toast'
import './globals.css'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster position='bottom-left'/>
        {children}
      </body>
    </html>
  )
}
